# Generated by Django 5.1.7 on 2025-03-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigIntegerField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
    ]
