# Generated by Django 5.1.7 on 2025-03-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_books_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
