# Generated by Django 5.1.7 on 2025-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_genre_book_summary_remove_readlist_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('novel', 'Novel')], max_length=25),
        ),
    ]
