# Generated by Django 5.1.7 on 2025-03-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('novel', 'Novel'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('crime', 'Crime')], max_length=25),
        ),
    ]
