# Generated by Django 5.1.7 on 2025-03-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_genre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, choices=[('literature', 'Literature'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('novel', 'Novel'), ('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery')], max_length=25),
        ),
    ]
