# Generated by Django 5.1.7 on 2025-03-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(default=1, upload_to='ebooks/'),
            preserve_default=False,
        ),
    ]
