# Generated by Django 5.1.7 on 2025-03-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_book_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
