# Generated by Django 5.1.7 on 2025-05-19 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_book_author_alter_book_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('TBR', 'TO READ'), ('Reading', 'Currently Reading'), ('Read', 'Read')], default='TBR', max_length=25),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('literature', 'Literature'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('novel', 'Novel'), ('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery')], max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='readlist',
            unique_together={('user', 'book')},
        ),
    ]
