# Generated by Django 5.1.7 on 2025-05-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='status',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
